name: Build curl

on:
  push:
#  workflow_dispatch:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies.
        run: |
          apt update
          apt install -y ninja-build
      - run: |
          .github/scripts/build_curl.sh

