name: Build curl v2

on:
  push:

jobs:
  build_linux_x64-gnu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Build
        run: |
          cd native_build
          PLATFORM=linux_x64 LIBC=gnu make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64-gnu
          path: |
            native_build/install/libcurl*

  test_linux_x64-gnu:
    runs-on: ubuntu-22.04
    needs: build_linux_x64-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: linux_x64-gnu
          path: native_build/install/
      - name: "Check"
        run: |
          ./gradlew check -si

  build_linux_x64-musl:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Build
        run: |
          cd native_build
          PLATFORM=linux_x64 LIBC=musl make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64-musl
          path: |
            native_build/install/libcurl*

  test_linux_x64-musl:
    runs-on: ubuntu-22.04
    needs: build_linux_x64-musl
    container:
      image: alpine:3.18
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: linux_x64-musl
          path: native_build/install/
      - name: "Check"
        run: |
          apk update && apk add openjdk8 openjdk9 openjdk17 git
          ./gradlew check -si

  build_linux_arm64-gnu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          sudo apt update
          sudo apt install gcc-10-aarch64-linux-gnu
      - name: Build
        run: |
          cd native_build
          PLATFORM=linux_arm64 LIBC=gnu make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_arm64-gnu
          path: |
            native_build/install/libcurl*

  test_linux_arm64-gnu:
    runs-on: ubuntu-22.04
    needs: build_linux_arm64-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: linux_arm64-gnu
          path: native_build/install/
      - uses: uraimo/run-on-arch-action@v2
        name: Check
        with:
          arch: aarch64
          distro: ubuntu22.04
          install: apt update && apt install -y openjdk-8-jdk-headless git
          run: |
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
            ./gradlew check -si

  build_windows_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          sudo apt update
          sudo apt install mingw-w64
      - name: Build
        run: |
          cd native_build
          PLATFORM=windows_x64 make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_x64
          path: |
            native_build/install/libcurl*

  test_windows_x64:
    runs-on: windows-2022
    needs: build_windows_x64
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: windows_x64
          path: native_build/install/
      - name: "Check"
        run: |
          ./gradlew check -si

  build_macos_x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          rm -rf /usr/local/Cellar/openssl*/**/include
          brew install make coreutils
      - name: Build
        run: |
          cd native_build
          PLATFORM=macos_x64 gmake
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos_x64
          path: |
            native_build/install/libcurl*

  test_macos_x64:
    runs-on: macos-11
    needs: build_macos_x64
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: macos_x64
          path: native_build/install/
      - name: "Check"
        run: |
          ./gradlew check -si

  build_macos_arm64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          rm -rf /usr/local/Cellar/openssl*/**/include
          brew install make coreutils
      - name: Build
        run: |
          cd native_build
          PLATFORM=macos_arm64 gmake
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos_arm64
          path: |
            native_build/install/libcurl*

  package:
    runs-on: ubuntu-22.04
    needs: [ build_linux_x64-gnu, test_linux_x64-gnu, build_linux_x64-musl, test_linux_x64-musl, build_linux_arm64-gnu, test_linux_arm64-gnu, build_windows_x64, test_windows_x64, build_macos_x64, test_macos_x64, build_macos_arm64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: actions/download-artifact@v3
        with:
          name: linux_x64-gnu
          path: native_build/install/
      - uses: actions/download-artifact@v3
        with:
          name: linux_x64-musl
          path: native_build/install/
      - uses: actions/download-artifact@v3
        with:
          name: linux_arm64-gnu
          path: native_build/install/
      - uses: actions/download-artifact@v3
        with:
          name: windows_x64
          path: native_build/install/
      - uses: actions/download-artifact@v3
        with:
          name: macos_x64
          path: native_build/install/
      - uses: actions/download-artifact@v3
        with:
          name: macos_arm64
          path: native_build/install/
      - name: Build
        run: ./gradlew jar jarWithLibCurl -si
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
        run: ./gradlew publish -si
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            build/**/*.jar
