name: Build

on:
  push:
#  pull_request:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Build and Test
        run: ./gradlew curl4jLinux_x64ReleaseSharedLibrary test testJ17 -si --no-daemon
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: |
            build/**/*.so

  build_linux_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: apt update && apt install -y openjdk-8-jdk-headless build-essential
          run: |
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
            ./gradlew curl4jLinux_arm64ReleaseSharedLibrary test testJ17 -si --console=plain --no-daemon
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_arm64
          path: |
            build/**/*.so

  build_windows_x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
      - run: |
          export JAVA_HOME=$(cygpath $JAVA_HOME)
          ./gradlew curl4jWindows_x64ReleaseSharedLibrary test testJ17 --no-daemon
        shell: msys2 {0}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_x64
          path: |
            build/**/*.dll

  build_macos_x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build and Test
        run: |
          brew install automake autoconf libtool dejagnu
          ./gradlew curl4jMacos_x64ReleaseSharedLibrary test testJ17 -si --no-daemon
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos_x64
          path: |
            build/**/*.dylib

  package:
    runs-on: ubuntu-22.04
    needs: [ build_linux_x64, build_linux_arm64, build_windows_x64, build_macos_x64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: linux_x64
          path: ./build/
      - uses: actions/download-artifact@v3
        with:
          name: linux_arm64
          path: ./build/
      - uses: actions/download-artifact@v3
        with:
          name: windows_x64
          path: ./build/
      - uses: actions/download-artifact@v3
        with:
          name: macos_x64
          path: ./build/
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Build
        run: ./gradlew jar -si
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            build/**/*.jar
