name: Build curl

on:
  workflow_dispatch:

env:
  FILE_SERVER: ${{ secrets.FILE_SERVER }}
  FILE_SERVER_USER: ${{ secrets.FILE_SERVER_USER }}
  FILE_SERVER_PASSWORD: ${{ secrets.FILE_SERVER_PASSWORD }}

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies.
        run: |
          sudo apt update
          sudo apt install -y ninja-build
      - run: |
          .github/scripts/build_curl.sh linux_x64

  build_linux_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            export FILE_SERVER=${{ secrets.FILE_SERVER }}
            export FILE_SERVER_USER=${{ secrets.FILE_SERVER_USER }}
            export FILE_SERVER_PASSWORD=${{ secrets.FILE_SERVER_PASSWORD }}
            apt update
            apt install -y build-essential curl git autoconf libtool cmake ninja-build zip unzip python3 pkgconf
            .github/scripts/build_curl.sh linux_arm64

  repack_windows_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies.
        run: .github/scripts/repack_curl_win64.sh

  build_macos_x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          rm -rf /usr/local/Cellar/openssl*/**/include
          brew install automake autoconf libtool cmake ninja coreutils
          .github/scripts/build_curl.sh macos_x64

# One day GitHub will make this easy for us.. For now, someone with an m1 runs the script manually.
#  build_macos_arm64:
#    runs-on: macos-11
#    steps:
#      - uses: actions/checkout@v3
#      - run: |
#          brew install automake autoconf libtool cmake ninja coreutils
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#          .github/scripts/build_curl.sh macos_arm64
