name: Build

on:
#  push:
  pull_request:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y texinfo
      - name: Build
        run: ./gradlew curl4jLinux_x86_64ReleaseSharedLibrary -si
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: |
            build/**/*.so

  build_linux_aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update && apt install -y openjdk-8-jdk-headless autoconf texinfo build-essential libtool
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
            ./gradlew curl4jLinux_arm64ReleaseSharedLibrary -si
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_arm64
          path: |
            build/**/*.so
