name: Build

on:
  push:
  pull_request:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install Dependencies
        run: apt update && apt install -y texinfo
      - name: Build
        run: ./gradlew curl4jLinux_x86_64ReleaseSharedLibrary
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: |
            build/**/*.so

  build_linux_aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: raspberrypi_zero2_w_arm64_w
          commands: |
            uname -a
