name: Build

on:
#  push:
  pull_request:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y texinfo
      - name: Build
        run: ./gradlew curl4jLinux_x86_64ReleaseSharedLibrary -si
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: |
            build/**/*.so

  build_linux_aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a53
          base_image: https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.3-preinstalled-server-arm64+raspi.img.xz
          commands: |
            sudo apt update && sudo apt install -y openjdk-8-jdk-headless
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
            ./gradlew curl4jLinux_x86_64ReleaseSharedLibrary -si
