name: Build curl

on:
  push:
#  workflow_dispatch:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies.
        run: |
          sudo apt update
          sudo apt install -y ninja-build
      - run: |
          .github/scripts/build_curl.sh

  build_linux_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update
            apt install -y build-essential curl git autoconf libtool cmake ninja-build zip unzip golang python3
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            .github/scripts/build_curl.sh

  build_macos_x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew install automake autoconf libtool cmake ninja coreutils
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          .github/scripts/build_curl.sh

# One day GitHub will make this easy for us.. For now, someone with an m1 runs the script manually.
#  build_macos_arm64:
#    runs-on: macos-11
#    steps:
#      - uses: actions/checkout@v3
#      - run: |
#          brew install automake autoconf libtool cmake ninja coreutils
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#          .github/scripts/build_curl.sh
