name: Build curl v2

on:
  push:

jobs:
  build_linux_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Build
        run: |
          cd native_build
          PLATFORM=linux_x64 make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: |
            native_build/install/libcurl*

  build_linux_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          sudo apt update
          sudo apt install gcc-10-aarch64-linux-gnu
      - name: Build
        run: |
          cd native_build
          PLATFORM=linux_arm64 make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_arm64
          path: |
            native_build/install/libcurl*

  build_windows_x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          sudo apt update
          sudo apt install mingw-w64
      - name: Build
        run: |
          cd native_build
          PLATFORM=windows_x64 make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_x64
          path: |
            native_build/install/libcurl*

  build_macos_x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          rm -rf /usr/local/Cellar/openssl*/**/include
          brew install make coreutils
      - name: Build
        run: |
          cd native_build
          PLATFORM=macos_x64 gmake
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos_x64
          path: |
            native_build/install/libcurl*

  build_macos_aarch64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-
      - name: Install dependencies.
        run: |
          rm -rf /usr/local/Cellar/openssl*/**/include
          brew install make coreutils
      - name: Build
        run: |
          cd native_build
          PLATFORM=macos_arm64 gmake
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos_arm64
          path: |
            native_build/install/libcurl*
